//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Controls/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""player"",
            ""id"": ""955be93d-7b31-45d9-b352-3b68d07484db"",
            ""actions"": [
                {
                    ""name"": ""move"",
                    ""type"": ""Value"",
                    ""id"": ""6da265d8-0921-42de-9ddd-cef8a38bd8b8"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""push"",
                    ""type"": ""Button"",
                    ""id"": ""02bc57d9-d96b-4f34-ac1c-cdea968f97bb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""look"",
                    ""type"": ""Value"",
                    ""id"": ""26c2c1fe-6273-4232-918b-b25f3afd152f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""brake"",
                    ""type"": ""Button"",
                    ""id"": ""0c56de17-4ed7-4434-9c95-0b6656e6a271"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""switch"",
                    ""type"": ""Button"",
                    ""id"": ""a3203d16-d2d6-4010-8687-ecb7eac347e7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""rightStick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""2b5fdc0f-4303-4b92-a6a6-29bba3fd010f"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ollieCrouch"",
                    ""type"": ""Button"",
                    ""id"": ""83528823-48cd-4d9d-99ec-528c5c805bfb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ollie"",
                    ""type"": ""Button"",
                    ""id"": ""ecd1b5fc-f94b-45e4-956a-b332c5a2cc42"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""debug.reset"",
                    ""type"": ""Button"",
                    ""id"": ""7fe96717-757f-4620-a12e-71f4cc6f6422"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""debug.die"",
                    ""type"": ""Button"",
                    ""id"": ""de8f906f-b125-4de3-9875-bf93861ae5e2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""debug.changeScene"",
                    ""type"": ""Button"",
                    ""id"": ""1b4cee34-57dc-4095-83ac-5b6911568313"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""debug.flyMode"",
                    ""type"": ""Button"",
                    ""id"": ""a2ce7473-b7ce-491c-9945-009c44d76e6d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""comboInputButton"",
                    ""type"": ""Button"",
                    ""id"": ""530bfe53-8772-4079-b991-fbb6ffc168f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""comboInputStick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""04bf4378-7df8-4ae4-9a57-b65e534f02ef"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f7d20f4d-8bd7-42cf-b892-22ac91f4bc64"",
                    ""path"": ""<Gamepad>/leftStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""gamepad"",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""f34da913-eeed-4979-8993-a6b711af0de9"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""2750fd05-1dfd-43e0-bf4b-e299212d30a6"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KB + M"",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""cea1042c-0c4e-4d5d-b779-57d9fa0c14ff"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KB + M"",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""581d9da0-12f2-4532-a13c-e05c221d0f07"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KB + M"",
                    ""action"": ""push"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""632ee420-e050-4699-99bb-cb69ad6eee1b"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""gamepad"",
                    ""action"": ""push"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5839f0d4-ede6-418b-9042-212fdc8edae1"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KB + M"",
                    ""action"": ""look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""secondary look"",
                    ""id"": ""80991ccc-9ddb-44d4-b213-35b27031e915"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""look"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""0006dda7-9b17-4d3a-9489-0428356e820d"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""gamepad"",
                    ""action"": ""look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""60f9244a-246b-4353-acba-e6deb1af0a75"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""gamepad"",
                    ""action"": ""look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""7ba19ec0-699e-4d3b-90f6-f82969743aed"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KB + M"",
                    ""action"": ""brake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""019a8676-99bf-4cc0-95df-f64619e53bfa"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""gamepad"",
                    ""action"": ""brake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b38bb221-c96f-48bc-83bb-c8bb9534b12f"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KB + M"",
                    ""action"": ""switch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e2176e7-e048-4738-8436-234430c8e915"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""gamepad"",
                    ""action"": ""switch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1d43e8e9-c993-43e8-b961-73d5511b98da"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""gamepad"",
                    ""action"": ""rightStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9313f699-0839-4aed-831a-555ed45236f8"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""gamepad"",
                    ""action"": ""ollie"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab7c3cd8-e37b-4fc8-949a-4b71c4fe71f6"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KB + M"",
                    ""action"": ""ollie"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c2eea51-ccf6-43b1-89c3-ef5d42a1c68a"",
                    ""path"": ""<Keyboard>/delete"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KB + M"",
                    ""action"": ""debug.die"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ba86e53-4462-4df8-946b-dd6ecfab645a"",
                    ""path"": ""<Keyboard>/home"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KB + M"",
                    ""action"": ""debug.changeScene"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""07d63a5c-0169-4121-b9c3-8ff9386446a7"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""debug.flyMode"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""b1f47d97-7fa8-4c70-8583-867ba2e8f3bb"",
                    ""path"": ""<Keyboard>/pageDown"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""debug.flyMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""e1ffa61f-eec1-4c0e-a4f5-be03cd2c7e91"",
                    ""path"": ""<Keyboard>/pageUp"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""debug.flyMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""94d3ce8e-189e-472f-aecf-6ab922a2b95a"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""gamepad"",
                    ""action"": ""comboInputButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd40acc2-3bc2-45d1-98ca-d16df9e639ac"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""gamepad"",
                    ""action"": ""comboInputButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ef8d155-0f66-41d9-bd52-e13f0a122906"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""gamepad"",
                    ""action"": ""comboInputButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d1b8638-7060-4ade-bd08-147bdcb08783"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""gamepad"",
                    ""action"": ""comboInputButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d5b4e2db-fead-42f8-bbd2-923144f517ba"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""gamepad"",
                    ""action"": ""comboInputButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f25fa96-a11e-4f72-9ebf-7f84c1b8d60c"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""gamepad"",
                    ""action"": ""comboInputButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d02bdc56-a043-4ffc-8c2c-ab922c689254"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""gamepad"",
                    ""action"": ""comboInputButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e17989f7-6ecd-465f-921d-1a7c64872e01"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""gamepad"",
                    ""action"": ""comboInputButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""385609b8-a99f-47d9-9430-2c2e1509fbe0"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""gamepad"",
                    ""action"": ""comboInputButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""64c71825-6f44-487a-8a05-93cbec774c86"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""gamepad"",
                    ""action"": ""comboInputButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46685f17-2da1-4662-8824-792eab5327f7"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""gamepad"",
                    ""action"": ""comboInputButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9547ef79-023b-420c-b86a-4fc82fc350e4"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""gamepad"",
                    ""action"": ""comboInputButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f5d2726c-bf9c-44ba-b621-958091bd4909"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""gamepad"",
                    ""action"": ""comboInputButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0159c7d8-66c6-49be-899d-be13fd320715"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""gamepad"",
                    ""action"": ""comboInputButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""054ecc07-6b2a-4480-a6db-73a265d0406c"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""gamepad"",
                    ""action"": ""comboInputStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c6998c7-2065-45c8-b8ad-793f52cc1d60"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""gamepad"",
                    ""action"": ""ollieCrouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c3ba339-daeb-42ad-9783-c57ac7f13633"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KB + M"",
                    ""action"": ""debug.reset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3313ee40-49ae-401c-a59a-cb7912aab2e2"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""gamepad"",
                    ""action"": ""debug.reset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""debugFly"",
            ""id"": ""cdc489b7-d901-4257-a0c3-4f7a0b12328c"",
            ""actions"": [
                {
                    ""name"": ""look"",
                    ""type"": ""Value"",
                    ""id"": ""694b1f77-1f3a-482a-8566-cea85e7296e1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""move"",
                    ""type"": ""Value"",
                    ""id"": ""6a8e62ef-691f-4743-927d-aa94b1b5c8a1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""vert"",
                    ""type"": ""Value"",
                    ""id"": ""f7b2d019-f2a1-4564-bcda-846d5d4c1ae6"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""stepBack"",
                    ""type"": ""Value"",
                    ""id"": ""c670d8de-5236-4acb-b002-dda465511ef2"",
                    ""expectedControlType"": ""Digital"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""stepForwards"",
                    ""type"": ""Value"",
                    ""id"": ""7daf7753-5fc9-4671-acec-f16e8ad9068a"",
                    ""expectedControlType"": ""Digital"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Debug.flyMode"",
                    ""type"": ""Button"",
                    ""id"": ""b48b1be0-a78b-4d8b-af48-c9d9996d2d08"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""increaseFrameWindow"",
                    ""type"": ""Button"",
                    ""id"": ""05994b31-5b46-47cd-86ce-22e03bf65b00"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""decreaseFrameWindow"",
                    ""type"": ""Button"",
                    ""id"": ""76e37466-950c-4445-89c9-24f160a8b320"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b10e8b83-2861-48bc-82cf-23595a386bec"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KB + M"",
                    ""action"": ""look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80c3cc0d-38f0-4f48-af10-a581c4ce5526"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=3,y=3)"",
                    ""groups"": ""gamepad"",
                    ""action"": ""look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""wasd"",
                    ""id"": ""d23856ef-a88e-49d9-bbeb-d8a89618f0de"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a7eefec0-386b-4fa9-8636-423fe56d7642"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KB + M"",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3bd850c4-ef89-4cf2-b8d1-d52c8b28bece"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KB + M"",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a498af03-5315-41d6-aaaf-0706c525555c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KB + M"",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d70e913a-a9d4-41c7-a4b9-9eb84bc951ca"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KB + M"",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b9c6db15-263e-43fa-a0d2-bca60641dfc4"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""keyb"",
                    ""id"": ""b457034c-34d9-46d6-b2d3-8544811d60ad"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""vert"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""af9e24c9-29dc-41f6-9e37-acdfd40937bc"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KB + M"",
                    ""action"": ""vert"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""a7c75297-97c4-4746-9481-e1e6eeaa35ce"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KB + M"",
                    ""action"": ""vert"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""cont"",
                    ""id"": ""9b4e3c3a-5074-4d0b-aaa9-e005001a6e8a"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""vert"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""893e7187-8941-4388-be60-8d844bb9401b"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""gamepad"",
                    ""action"": ""vert"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""43450265-c7fc-4135-b5ac-08922098b092"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""gamepad"",
                    ""action"": ""vert"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9dcac7ea-40b5-47e3-ac91-ca32900a74d0"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KB + M"",
                    ""action"": ""stepBack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2aee82b-127e-4ca9-bd7c-27be637a0494"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""gamepad"",
                    ""action"": ""stepBack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d6c5e622-81cd-495d-b530-15f45f403484"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KB + M"",
                    ""action"": ""stepForwards"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""ab330e0e-2a32-460f-b733-338bd608aab4"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Debug.flyMode"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""3f0f1d57-9f46-43a0-8798-c036be2779a0"",
                    ""path"": ""<Keyboard>/pageDown"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Debug.flyMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""4802cc8a-a2fa-4f5b-a254-cddbdc9e59a7"",
                    ""path"": ""<Keyboard>/pageUp"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Debug.flyMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5203f131-89cb-46ee-8815-f2e19e5f8e9a"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""gamepad"",
                    ""action"": ""decreaseFrameWindow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f64ab51d-8056-4515-97e1-b619aab184c4"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KB + M"",
                    ""action"": ""decreaseFrameWindow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99f67932-eb7a-4884-b898-0bb17a702009"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KB + M"",
                    ""action"": ""increaseFrameWindow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4942d92-6a65-4b0a-9da6-d98669b429b4"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""gamepad"",
                    ""action"": ""increaseFrameWindow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dfb28c93-dedb-49d1-833e-7a4e62bb2c3c"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""gamepad"",
                    ""action"": ""stepForwards"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""KB + M"",
            ""bindingGroup"": ""KB + M"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""gamepad"",
            ""bindingGroup"": ""gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // player
        m_player = asset.FindActionMap("player", throwIfNotFound: true);
        m_player_move = m_player.FindAction("move", throwIfNotFound: true);
        m_player_push = m_player.FindAction("push", throwIfNotFound: true);
        m_player_look = m_player.FindAction("look", throwIfNotFound: true);
        m_player_brake = m_player.FindAction("brake", throwIfNotFound: true);
        m_player_switch = m_player.FindAction("switch", throwIfNotFound: true);
        m_player_rightStick = m_player.FindAction("rightStick", throwIfNotFound: true);
        m_player_ollieCrouch = m_player.FindAction("ollieCrouch", throwIfNotFound: true);
        m_player_ollie = m_player.FindAction("ollie", throwIfNotFound: true);
        m_player_debugreset = m_player.FindAction("debug.reset", throwIfNotFound: true);
        m_player_debugdie = m_player.FindAction("debug.die", throwIfNotFound: true);
        m_player_debugchangeScene = m_player.FindAction("debug.changeScene", throwIfNotFound: true);
        m_player_debugflyMode = m_player.FindAction("debug.flyMode", throwIfNotFound: true);
        m_player_comboInputButton = m_player.FindAction("comboInputButton", throwIfNotFound: true);
        m_player_comboInputStick = m_player.FindAction("comboInputStick", throwIfNotFound: true);
        // debugFly
        m_debugFly = asset.FindActionMap("debugFly", throwIfNotFound: true);
        m_debugFly_look = m_debugFly.FindAction("look", throwIfNotFound: true);
        m_debugFly_move = m_debugFly.FindAction("move", throwIfNotFound: true);
        m_debugFly_vert = m_debugFly.FindAction("vert", throwIfNotFound: true);
        m_debugFly_stepBack = m_debugFly.FindAction("stepBack", throwIfNotFound: true);
        m_debugFly_stepForwards = m_debugFly.FindAction("stepForwards", throwIfNotFound: true);
        m_debugFly_DebugflyMode = m_debugFly.FindAction("Debug.flyMode", throwIfNotFound: true);
        m_debugFly_increaseFrameWindow = m_debugFly.FindAction("increaseFrameWindow", throwIfNotFound: true);
        m_debugFly_decreaseFrameWindow = m_debugFly.FindAction("decreaseFrameWindow", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // player
    private readonly InputActionMap m_player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_player_move;
    private readonly InputAction m_player_push;
    private readonly InputAction m_player_look;
    private readonly InputAction m_player_brake;
    private readonly InputAction m_player_switch;
    private readonly InputAction m_player_rightStick;
    private readonly InputAction m_player_ollieCrouch;
    private readonly InputAction m_player_ollie;
    private readonly InputAction m_player_debugreset;
    private readonly InputAction m_player_debugdie;
    private readonly InputAction m_player_debugchangeScene;
    private readonly InputAction m_player_debugflyMode;
    private readonly InputAction m_player_comboInputButton;
    private readonly InputAction m_player_comboInputStick;
    public struct PlayerActions
    {
        private @Controls m_Wrapper;
        public PlayerActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @move => m_Wrapper.m_player_move;
        public InputAction @push => m_Wrapper.m_player_push;
        public InputAction @look => m_Wrapper.m_player_look;
        public InputAction @brake => m_Wrapper.m_player_brake;
        public InputAction @switch => m_Wrapper.m_player_switch;
        public InputAction @rightStick => m_Wrapper.m_player_rightStick;
        public InputAction @ollieCrouch => m_Wrapper.m_player_ollieCrouch;
        public InputAction @ollie => m_Wrapper.m_player_ollie;
        public InputAction @debugreset => m_Wrapper.m_player_debugreset;
        public InputAction @debugdie => m_Wrapper.m_player_debugdie;
        public InputAction @debugchangeScene => m_Wrapper.m_player_debugchangeScene;
        public InputAction @debugflyMode => m_Wrapper.m_player_debugflyMode;
        public InputAction @comboInputButton => m_Wrapper.m_player_comboInputButton;
        public InputAction @comboInputStick => m_Wrapper.m_player_comboInputStick;
        public InputActionMap Get() { return m_Wrapper.m_player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @move.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @move.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @move.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @push.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPush;
                @push.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPush;
                @push.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPush;
                @look.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @look.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @look.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @brake.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBrake;
                @brake.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBrake;
                @brake.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBrake;
                @switch.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch;
                @switch.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch;
                @switch.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch;
                @rightStick.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightStick;
                @rightStick.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightStick;
                @rightStick.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightStick;
                @ollieCrouch.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnOllieCrouch;
                @ollieCrouch.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnOllieCrouch;
                @ollieCrouch.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnOllieCrouch;
                @ollie.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnOllie;
                @ollie.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnOllie;
                @ollie.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnOllie;
                @debugreset.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDebugreset;
                @debugreset.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDebugreset;
                @debugreset.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDebugreset;
                @debugdie.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDebugdie;
                @debugdie.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDebugdie;
                @debugdie.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDebugdie;
                @debugchangeScene.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDebugchangeScene;
                @debugchangeScene.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDebugchangeScene;
                @debugchangeScene.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDebugchangeScene;
                @debugflyMode.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDebugflyMode;
                @debugflyMode.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDebugflyMode;
                @debugflyMode.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDebugflyMode;
                @comboInputButton.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnComboInputButton;
                @comboInputButton.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnComboInputButton;
                @comboInputButton.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnComboInputButton;
                @comboInputStick.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnComboInputStick;
                @comboInputStick.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnComboInputStick;
                @comboInputStick.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnComboInputStick;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @move.started += instance.OnMove;
                @move.performed += instance.OnMove;
                @move.canceled += instance.OnMove;
                @push.started += instance.OnPush;
                @push.performed += instance.OnPush;
                @push.canceled += instance.OnPush;
                @look.started += instance.OnLook;
                @look.performed += instance.OnLook;
                @look.canceled += instance.OnLook;
                @brake.started += instance.OnBrake;
                @brake.performed += instance.OnBrake;
                @brake.canceled += instance.OnBrake;
                @switch.started += instance.OnSwitch;
                @switch.performed += instance.OnSwitch;
                @switch.canceled += instance.OnSwitch;
                @rightStick.started += instance.OnRightStick;
                @rightStick.performed += instance.OnRightStick;
                @rightStick.canceled += instance.OnRightStick;
                @ollieCrouch.started += instance.OnOllieCrouch;
                @ollieCrouch.performed += instance.OnOllieCrouch;
                @ollieCrouch.canceled += instance.OnOllieCrouch;
                @ollie.started += instance.OnOllie;
                @ollie.performed += instance.OnOllie;
                @ollie.canceled += instance.OnOllie;
                @debugreset.started += instance.OnDebugreset;
                @debugreset.performed += instance.OnDebugreset;
                @debugreset.canceled += instance.OnDebugreset;
                @debugdie.started += instance.OnDebugdie;
                @debugdie.performed += instance.OnDebugdie;
                @debugdie.canceled += instance.OnDebugdie;
                @debugchangeScene.started += instance.OnDebugchangeScene;
                @debugchangeScene.performed += instance.OnDebugchangeScene;
                @debugchangeScene.canceled += instance.OnDebugchangeScene;
                @debugflyMode.started += instance.OnDebugflyMode;
                @debugflyMode.performed += instance.OnDebugflyMode;
                @debugflyMode.canceled += instance.OnDebugflyMode;
                @comboInputButton.started += instance.OnComboInputButton;
                @comboInputButton.performed += instance.OnComboInputButton;
                @comboInputButton.canceled += instance.OnComboInputButton;
                @comboInputStick.started += instance.OnComboInputStick;
                @comboInputStick.performed += instance.OnComboInputStick;
                @comboInputStick.canceled += instance.OnComboInputStick;
            }
        }
    }
    public PlayerActions @player => new PlayerActions(this);

    // debugFly
    private readonly InputActionMap m_debugFly;
    private IDebugFlyActions m_DebugFlyActionsCallbackInterface;
    private readonly InputAction m_debugFly_look;
    private readonly InputAction m_debugFly_move;
    private readonly InputAction m_debugFly_vert;
    private readonly InputAction m_debugFly_stepBack;
    private readonly InputAction m_debugFly_stepForwards;
    private readonly InputAction m_debugFly_DebugflyMode;
    private readonly InputAction m_debugFly_increaseFrameWindow;
    private readonly InputAction m_debugFly_decreaseFrameWindow;
    public struct DebugFlyActions
    {
        private @Controls m_Wrapper;
        public DebugFlyActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @look => m_Wrapper.m_debugFly_look;
        public InputAction @move => m_Wrapper.m_debugFly_move;
        public InputAction @vert => m_Wrapper.m_debugFly_vert;
        public InputAction @stepBack => m_Wrapper.m_debugFly_stepBack;
        public InputAction @stepForwards => m_Wrapper.m_debugFly_stepForwards;
        public InputAction @DebugflyMode => m_Wrapper.m_debugFly_DebugflyMode;
        public InputAction @increaseFrameWindow => m_Wrapper.m_debugFly_increaseFrameWindow;
        public InputAction @decreaseFrameWindow => m_Wrapper.m_debugFly_decreaseFrameWindow;
        public InputActionMap Get() { return m_Wrapper.m_debugFly; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DebugFlyActions set) { return set.Get(); }
        public void SetCallbacks(IDebugFlyActions instance)
        {
            if (m_Wrapper.m_DebugFlyActionsCallbackInterface != null)
            {
                @look.started -= m_Wrapper.m_DebugFlyActionsCallbackInterface.OnLook;
                @look.performed -= m_Wrapper.m_DebugFlyActionsCallbackInterface.OnLook;
                @look.canceled -= m_Wrapper.m_DebugFlyActionsCallbackInterface.OnLook;
                @move.started -= m_Wrapper.m_DebugFlyActionsCallbackInterface.OnMove;
                @move.performed -= m_Wrapper.m_DebugFlyActionsCallbackInterface.OnMove;
                @move.canceled -= m_Wrapper.m_DebugFlyActionsCallbackInterface.OnMove;
                @vert.started -= m_Wrapper.m_DebugFlyActionsCallbackInterface.OnVert;
                @vert.performed -= m_Wrapper.m_DebugFlyActionsCallbackInterface.OnVert;
                @vert.canceled -= m_Wrapper.m_DebugFlyActionsCallbackInterface.OnVert;
                @stepBack.started -= m_Wrapper.m_DebugFlyActionsCallbackInterface.OnStepBack;
                @stepBack.performed -= m_Wrapper.m_DebugFlyActionsCallbackInterface.OnStepBack;
                @stepBack.canceled -= m_Wrapper.m_DebugFlyActionsCallbackInterface.OnStepBack;
                @stepForwards.started -= m_Wrapper.m_DebugFlyActionsCallbackInterface.OnStepForwards;
                @stepForwards.performed -= m_Wrapper.m_DebugFlyActionsCallbackInterface.OnStepForwards;
                @stepForwards.canceled -= m_Wrapper.m_DebugFlyActionsCallbackInterface.OnStepForwards;
                @DebugflyMode.started -= m_Wrapper.m_DebugFlyActionsCallbackInterface.OnDebugflyMode;
                @DebugflyMode.performed -= m_Wrapper.m_DebugFlyActionsCallbackInterface.OnDebugflyMode;
                @DebugflyMode.canceled -= m_Wrapper.m_DebugFlyActionsCallbackInterface.OnDebugflyMode;
                @increaseFrameWindow.started -= m_Wrapper.m_DebugFlyActionsCallbackInterface.OnIncreaseFrameWindow;
                @increaseFrameWindow.performed -= m_Wrapper.m_DebugFlyActionsCallbackInterface.OnIncreaseFrameWindow;
                @increaseFrameWindow.canceled -= m_Wrapper.m_DebugFlyActionsCallbackInterface.OnIncreaseFrameWindow;
                @decreaseFrameWindow.started -= m_Wrapper.m_DebugFlyActionsCallbackInterface.OnDecreaseFrameWindow;
                @decreaseFrameWindow.performed -= m_Wrapper.m_DebugFlyActionsCallbackInterface.OnDecreaseFrameWindow;
                @decreaseFrameWindow.canceled -= m_Wrapper.m_DebugFlyActionsCallbackInterface.OnDecreaseFrameWindow;
            }
            m_Wrapper.m_DebugFlyActionsCallbackInterface = instance;
            if (instance != null)
            {
                @look.started += instance.OnLook;
                @look.performed += instance.OnLook;
                @look.canceled += instance.OnLook;
                @move.started += instance.OnMove;
                @move.performed += instance.OnMove;
                @move.canceled += instance.OnMove;
                @vert.started += instance.OnVert;
                @vert.performed += instance.OnVert;
                @vert.canceled += instance.OnVert;
                @stepBack.started += instance.OnStepBack;
                @stepBack.performed += instance.OnStepBack;
                @stepBack.canceled += instance.OnStepBack;
                @stepForwards.started += instance.OnStepForwards;
                @stepForwards.performed += instance.OnStepForwards;
                @stepForwards.canceled += instance.OnStepForwards;
                @DebugflyMode.started += instance.OnDebugflyMode;
                @DebugflyMode.performed += instance.OnDebugflyMode;
                @DebugflyMode.canceled += instance.OnDebugflyMode;
                @increaseFrameWindow.started += instance.OnIncreaseFrameWindow;
                @increaseFrameWindow.performed += instance.OnIncreaseFrameWindow;
                @increaseFrameWindow.canceled += instance.OnIncreaseFrameWindow;
                @decreaseFrameWindow.started += instance.OnDecreaseFrameWindow;
                @decreaseFrameWindow.performed += instance.OnDecreaseFrameWindow;
                @decreaseFrameWindow.canceled += instance.OnDecreaseFrameWindow;
            }
        }
    }
    public DebugFlyActions @debugFly => new DebugFlyActions(this);
    private int m_KBMSchemeIndex = -1;
    public InputControlScheme KBMScheme
    {
        get
        {
            if (m_KBMSchemeIndex == -1) m_KBMSchemeIndex = asset.FindControlSchemeIndex("KB + M");
            return asset.controlSchemes[m_KBMSchemeIndex];
        }
    }
    private int m_gamepadSchemeIndex = -1;
    public InputControlScheme gamepadScheme
    {
        get
        {
            if (m_gamepadSchemeIndex == -1) m_gamepadSchemeIndex = asset.FindControlSchemeIndex("gamepad");
            return asset.controlSchemes[m_gamepadSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnPush(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnBrake(InputAction.CallbackContext context);
        void OnSwitch(InputAction.CallbackContext context);
        void OnRightStick(InputAction.CallbackContext context);
        void OnOllieCrouch(InputAction.CallbackContext context);
        void OnOllie(InputAction.CallbackContext context);
        void OnDebugreset(InputAction.CallbackContext context);
        void OnDebugdie(InputAction.CallbackContext context);
        void OnDebugchangeScene(InputAction.CallbackContext context);
        void OnDebugflyMode(InputAction.CallbackContext context);
        void OnComboInputButton(InputAction.CallbackContext context);
        void OnComboInputStick(InputAction.CallbackContext context);
    }
    public interface IDebugFlyActions
    {
        void OnLook(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnVert(InputAction.CallbackContext context);
        void OnStepBack(InputAction.CallbackContext context);
        void OnStepForwards(InputAction.CallbackContext context);
        void OnDebugflyMode(InputAction.CallbackContext context);
        void OnIncreaseFrameWindow(InputAction.CallbackContext context);
        void OnDecreaseFrameWindow(InputAction.CallbackContext context);
    }
}
